//! Resolves `CARGO_PKG_NAME` (e.g. `flash-algo-v0` → family `v0`) against
//! `../../chips.yaml` and writes region constants to `$OUT_DIR/constants.rs`.

use std::{collections::BTreeMap, env, fs, path::PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct Chips {
    families: BTreeMap<String, Family>,
}

#[derive(Deserialize)]
struct Family {
    page_size: u32,
    word_size: u32,
    sys: Vec<Region>,
    opt: Region,
    vnd: Region,
}

#[derive(Deserialize)]
struct Region {
    addr: u32,
    size: u32,
}

pub fn generate() {
    let family = env::var("CARGO_PKG_NAME")
        .expect("CARGO_PKG_NAME unset")
        .strip_prefix("flash-algo-")
        .expect("crate name must start with `flash-algo-`")
        .to_owned();

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let chips_yaml = manifest_dir
        .join("..")
        .join("..")
        .join("chips.yaml")
        .canonicalize()
        .expect("locating chips.yaml");

    let raw = fs::read_to_string(&chips_yaml).expect("reading chips.yaml");
    let chips: Chips = serde_yaml::from_str(&raw).expect("parsing chips.yaml");
    let f = chips
        .families
        .get(&family)
        .unwrap_or_else(|| panic!("family `{family}` not in chips.yaml"));

    let primary_sys = f.sys.first().expect("at least one sys region");

    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("constants.rs");
    let body = format!(
        "// AUTO-GENERATED by flash-algo-build from chips.yaml — do not edit.\n\
         pub const PAGE_SIZE: u32 = {page};\n\
         pub const WORD: u32 = {word};\n\
         \n\
         pub const SYS_BASE: u32 = 0x{sys_addr:08X};\n\
         pub const SYS_SIZE: u32 = 0x{sys_size:X};\n\
         \n\
         pub const OPT_BASE: u32 = 0x{opt_addr:08X};\n\
         pub const OPT_SIZE: u32 = 0x{opt_size:X};\n\
         \n\
         pub const VND_BASE: u32 = 0x{vnd_addr:08X};\n\
         pub const VND_SIZE: u32 = 0x{vnd_size:X};\n",
        page = f.page_size,
        word = f.word_size,
        sys_addr = primary_sys.addr,
        sys_size = primary_sys.size,
        opt_addr = f.opt.addr,
        opt_size = f.opt.size,
        vnd_addr = f.vnd.addr,
        vnd_size = f.vnd.size,
    );
    fs::write(&out, body).expect("writing constants.rs");

    println!("cargo:rerun-if-changed={}", chips_yaml.display());
    println!("cargo:rerun-if-changed=build.rs");
}
